version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  log-generator:
    build:
      context: ../log-generator
      dockerfile: Dockerfile
    depends_on:
      - kafka

  log-consumer:
    build:
      context: ../log-consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"